/**
 * OuiMouve API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PersonalVehicleCreateDto {
  id?: number;
  immatriculation?: string;
  seats?: number;
  color?: string;
  description?: string;
  userId?: number;
}
