/**
 * OuiMouve API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdressDto { 
    id?: number;
    label?: string;
    city?: string;
    latX?: number;
    longY?: number;
    siteId?: number;
    departuresId?: Array<number>;
    arrivalsId?: Array<number>;
}

