/**
 * OuiMouve API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdressDto } from './adressDto';


export interface CarPoolingResponseDto { 
    id?: number;
    departure?: string;
    arrival?: string;
    status?: CarPoolingResponseDto.StatusEnum;
    durationInMinutes?: number;
    distance?: number;
    departureAddress?: AdressDto;
    destinationAddress?: AdressDto;
    organizerId?: number;
}
export namespace CarPoolingResponseDto {
    export const StatusEnum = {
        InProgress: 'IN_PROGRESS',
        Finished: 'FINISHED',
        Cancelled: 'CANCELLED',
        BookingOpen: 'BOOKING_OPEN',
        BookingFull: 'BOOKING_FULL'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


