/**
 * OuiMouve API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelDto { 
    id?: number;
    modelName?: string;
    mark?: string;
    photoURL?: string;
    motorType?: string;
    category?: ModelDto.CategoryEnum;
    seatsModel?: number;
    co2?: number;
}
export namespace ModelDto {
    export const CategoryEnum = {
        MicroUrbane: 'MICRO_URBANE',
        MiniCitadine: 'MINI_CITADINE',
        CitadinePolyvalente: 'CITADINE_POLYVALENTE',
        Compacte: 'COMPACTE',
        BerlineTailleS: 'BERLINE_TAILLE_S',
        BerlineTailleM: 'BERLINE_TAILLE_M',
        BerlineTailleL: 'BERLINE_TAILLE_L',
        SuvToutTerrainEtPickup: 'SUV_TOUT_TERRAIN_ET_PICKUP'
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
}


