/**
 * OuiMouve API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';


export interface PersonalVehicleDto { 
    id?: number;
    immatriculation?: string;
    seats?: number;
    color?: string;
    description?: string;
    user?: UserDto;
}

