/**
 * OuiMouve API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceVehicleDto } from './serviceVehicleDto';


export interface ReparationResponseDto { 
    id?: number;
    start?: string;
    end?: string;
    motive?: string;
    vehicle?: ServiceVehicleDto;
}

