/**
 * OuiMouve API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelDto } from './modelDto';
import { SiteResponseDto } from './siteResponseDto';


export interface ServiceVehicleDto { 
    id?: number;
    immatriculation?: string;
    seats?: number;
    status?: ServiceVehicleDto.StatusEnum;
    model?: ModelDto;
    mark?: string;
    site?: SiteResponseDto;
    siteName?: string;
}
export namespace ServiceVehicleDto {
    export const StatusEnum = {
        Disabled: 'DISABLED',
        Enabled: 'ENABLED',
        Booked: 'BOOKED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


