/**
 * OuiMouve API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServiceVehicleCreateDto { 
    id?: number;
    immatriculation?: string;
    seats?: number;
    status?: ServiceVehicleCreateDto.StatusEnum;
    modelId?: number;
    modelName?: string;
    mark?: string;
    siteId?: number;
    siteName?: string;
}
export namespace ServiceVehicleCreateDto {
    export const StatusEnum = {
        Disabled: 'DISABLED',
        Enabled: 'ENABLED',
        Booked: 'BOOKED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


