/**
 * OuiMouve API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SiteCreateDto { 
    name?: string;
    adressId?: number;
    vehicleIds?: Array<number>;
}

