/**
 * OuiMouve API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdressDto } from './adressDto';


export interface SiteResponseDto { 
    id?: number;
    name?: string;
    adress?: AdressDto;
    vehicleIds?: Array<number>;
}

