/**
 * OuiMouve API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VehicleReservationCreateDto { 
    serviceVehicleId?: number;
    userId?: number;
    start?: string;
    end?: string;
    status?: VehicleReservationCreateDto.StatusEnum;
}
export namespace VehicleReservationCreateDto {
    export const StatusEnum = {
        Disabled: 'DISABLED',
        Enabled: 'ENABLED',
        Booked: 'BOOKED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


