/**
 * OuiMouve API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceVehicleDto } from './serviceVehicleDto';
import { UserDto } from './userDto';


export interface VehicleReservationDto { 
    id?: number;
    serviceVehicle?: ServiceVehicleDto;
    user?: UserDto;
    start?: string;
    end?: string;
    status?: VehicleReservationDto.StatusEnum;
}
export namespace VehicleReservationDto {
    export const StatusEnum = {
        Disabled: 'DISABLED',
        Enabled: 'ENABLED',
        Booked: 'BOOKED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


